# PickPack configuration

# Address/port to use to reconnect players to:
# Replace these with the address/port you would need for the Geyser server.
address: 127.0.0.1
port: 19132

# Defaults, can be changed by players:
show-pack-descriptions: true
use-transfer-packet: true

# Command permissions:
# pickpack.reload: Permission to reload the config with /pickpack reload
reload-permission: "pickpack.reload"

# pickpack.menu: Permission for /pickpack menu. Blank is for all Bedrock players.
menu-permission: " "

# pickpack.default: Permission for /pickpack default. Blank is for all Bedrock players.
default-permission: " "

translations:
  menu-command-description: "Choose your own packs"
  reset-command-description: "Reset your packs to the default packs"
  reload-command-description: "Reload the config"

  main-menu-title: "Your current packs:"
  main-menu-change-button: "Change packs"
  main-menu-back-button: "Back"
  main-menu-select-button: "Select packs"

  filter-form-title: "Which packs would you like to use?"
  filter-button-name: "Filter"
  filter-all-packs: "all packs"
  filter-not-applied-packs: "not applied packs"
  filter-applied-packs: "applied packs"
  filter-description-toggle: "Show pack descriptions"
  filter-transfer-warning: "If the transfer packet does not work for you, you can disable it here."
  filter-transfer-toggle: "Use transfer packet"

  pack-form-title: "Choose your packs:"
  pack-form-label: "§l§2 showing§r§l§6 %filter% §r"
  no-packs-warning: "You have no packs applied!"

  disconnect-message: "§6 Join back to apply the changes!"
  reload-message: "§6 Config reloaded!"



