name: Build and Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build Shadow JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar --parallel

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-jar
          path: build/libs/*.jar

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            build/libs/*.jar
